config/routes.rb
Rails.application.routes.draw do
  get "/" => "welcome#index"
  
  resources :games, except: [:index] do
    resources :players, only: [:new, :create, :update, :destroy]
  end

  resources :game_masters, except: [:index, :destroy]

  root "welcome#index"

#################################

  get "login" => "sessions#new"
  post "login" => "sessions#create"

  get "logout" => "sessions#destroy"

#################################

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players, dependent: :destroy
  has_many :hooks, dependent: :destroy
  belongs_to :game_master

  validates :description, presence: true
end

app/models/game_master.rb
class GameMaster < ActiveRecord::Base
  has_many :games
  has_many :parties, through: :games
  has_many :players, through: :parties

  validates :username, :email, :password_digest, presence: true
  validates :username, :email, uniqueness: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/, message: "Must be valid email address" }

  has_secure_password
end   

app/models/hook.rb
class Hook < ActiveRecord::Base
  belongs_to :game
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include GameMastersHelper

  private
    def current_gm
      @game_master = GameMaster.find_by(id: session[:game_master_id])
    end

    def logged_in?
      session[:game_master_id]
    end

    helper_method :current_gm, :logged_in?

    protect_from_forgery with: :exception
end

app/controllers/game_masters_controller.rb
class GameMastersController < ApplicationController
  def new
    @game_master = GameMaster.new
  end

  def create
    @game_master = GameMaster.new(game_master_params)

    if @game_master.save
      session[:game_master_id] = @game_master.id
      redirect_to @game_master
    else
      flash[:danger] = "Registration failed!"
      render "new"
    end
  end

  def show
    @game_master = GameMaster.find_by(id: params[:id])
  end

  private

    def game_master_params
      params.require(:game_master).permit(:username, :email, :password)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_gm.games.create(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :city, :state, :bookmark)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :set_game

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)
  end


  def update
    @player = Player.find_by(id: params[:player_id])
  end

  def destroy
  end

  private

  def player_params
    params.require(:player).permit(:name, :dexterity, :vitality, :logic, :willpower, :charisma, :empathy, :pos_features, :neg_features, :equipment)
  end

  def set_game
    @game = Game.find(params[:game_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @game_master = GameMaster.find_by(email: params[:session][:email].downcase)
    if @game_master && @game_master.authenticate(password: params[:session][:password])
      session[:game_master_id] = @game_master.id
      redirect_to @game_master
    else
      flash[:danger] = "Game Master not found!"
      render "new"
    end
  end

  def destroy
    session[:game_master_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @games = Game.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_masters_helper.rb
module GameMastersHelper
  def current_gm
    @game_master = GameMaster.find_by(id: session[:game_master_id])
  end

  def logged_in?
    session[:game_master_id]
  end
end

app/helpers/games_helper.rb
module GamesHelper

  def game_creator?
    logged_in? && current_gm.id == @game.game_master.id
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/game_masters/new.html.erb
<div class="container">
  <h1 class="rock-font">Register</h1><br>

  <%= render 'form' %>

  <%= link_to 'Back', root_path %>
</div>

app/views/game_masters/show.html.erb
<div class="container">
  <h1 class="rock-font"><%= @game_master.username %>'s Games:</h1><br>
  <% if @game_master.games.empty? %>
    <h3>Not currently running any games.</h3>
  <% else %>
    <% @game_master.games.each do |game| %>
      <div class="panel panel-inverted container">
        <div class="panel-heading">
          <h3 class="panel-title"><%= link_to "#{game.name}", game_path(game.id) %></h3>
        </div>
        <div class="panel-body game-wrapper">
            Play time: <%= time_ago_in_words(game.created_at) %><br>
            Current Players: 
            <% if game.players.empty? %>
              0<br>
            <% else %>
              <%= game.players.length %><br>
            <% end %>
            <%= game.description %><br><br>
            <%= game.city %>, <%= game.state %><br><br>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= button_to "Start new game", new_game_path, {method: "get"} %>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <div class="textarea">
      <%= f.text_area :description %><br>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="container">
  <h1>Editing Game</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @game %> |
  <%= link_to 'Back', games_path %>
</div>

app/views/games/new.html.erb
<div class="container">

  <section class="form">
    <h1>New Game</h1>
    <%= render 'form' %>

    <%= link_to 'Back', games_path %>
  </section>

  <section class="instructions">
    <h1>Step One:</h1>
    This is the first step in creating a new game. Here you can fill out the basic details of the game, give it a title, list your location to share ideas with other local GMs and integrate with Google Maps, and give a short description of your scenario. 

    <p>This will all be displayed on your main game page, which is also where you will add your <span class="bold">PCs</span>, <span class="bold">Hooks</span>, <span class="bold">Bookmarks</span>, <span class="bold">NPCs</span>, and <span class="bold">Zombies</span>.</p>
  </section>

</div>

app/views/games/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1 class="rock-font"><%= @game.name %></h1>
  <p>Started on <%= @game.created_at.strftime("%B %d, %Y") %></p>
  <p><%= @game.description %></p>
  <h3 class="underline">Players:</h3>
  <% if @game.players.any? %>
    <% @game.players.each do |player| %>
      <div class="player-card col-lg-3 col-sm-12">

        <div class="player-name">
          <%= player.name %>
        </div>

        <div class="stats">
          <span class="phys">
            Dex <%= player.dexterity %> / <%= player.vitality %> Vit
          </span>
          <span class="ment">
            Log <%= player.logic %> / <%= player.willpower %> WPow
          </span>
          <span class="soc">
            Char <%= player.charisma %> / <%= player.empathy %> Emp
          </span>
        </div>

        <div class="features">
          + Features: <%= player.pos_features %><br>
          - Features: <%= player.neg_features %><br>
          Equipment: <%= player.equipment %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No current players, you should create some.</p>
  <% end %>
  <% if game_creator? %>
    <%= link_to "Create Player", new_game_player_path(@game) %>
    <%= link_to 'Edit', edit_game_path(@game) %> |
  <% end %>
  <%= link_to 'Back', root_path %>
  <% if @game.hooks.any? %>
    <h3 class="underline">Hooks:</h3>
    <% @game.hooks.each do |hook| %>
      <div class="col-lg-12">
        <p class="hook"><%= hook.description %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieFodder</title>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/assets/application.css" media="all">
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
          <% if logged_in? %>
            <li><%= link_to "#{current_gm.username}", current_gm %></li>
            <li><a href="/logout">Log out</a></li>
          <% else %>
            <li><a href="/login">Log in</a></li>
            <li><a href="/game_masters/new">Register</a></li>
          <% end %>
        </ul>
      </div>
    </nav>

  <%= yield %>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for([@game, @player]) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dexterity %>
    <%= f.text_field :dexterity %>
  </div>
  <div class="field">
    <%= f.label :vitality %>
    <%= f.text_field :vitality %>
  </div>
  <div class="field">
    <%= f.label :logic %>
    <%= f.text_field :logic %>
  </div>
  <div class="field">
    <%= f.label :willpower %>
    <%= f.text_field :willpower %>
  </div>
  <div class="field">
    <%= f.label :charisma %>
    <%= f.text_field :charisma %>
  </div>
  <div class="field">
    <%= f.label :empathy %>
    <%= f.text_field :empathy %>
  </div>
  <div class="field">
    <%= f.label :pos_features %>
    <%= f.text_field :pos_features %>
  </div>
  <div class="field">
    <%= f.label :neg_features %>
    <%= f.text_field :neg_features %>
  </div>
  <div class="field">
    <%= f.label :equipment %>
    <%= f.text_area :equipment %>
  </div>
<% end %>

app/views/players/new.html.erb
<div class="container">
  <h1>New Player</h1>
  <%= render "form" %>

  <%= link_to "Back", @game %>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Zombie Fodder</h1>
    <div class="opaque">
      <p>Zombie fodder is an unofficial companion app for the Fantasy Flight tabletop RPG, <strong>The End of the World</strong>&#8482;
      </p>

      <p>Register and log in to access your current sessions and see all current public games.

      Create your own game sessions with current party members, story hooks, NPCs, randomly generated or customized zombie enemies, bookmark details for picking up where the game is left off.</p>

      <p>This is a work in progress, so feel free to email me with suggestions, or submit a pull request on the github repo.</p>

      <p>Single-origin coffee slow-carb bespoke, lumbersexual fashion axe normcore vegan meh blog vinyl synth roof party squid etsy. Kale chips blue bottle pabst flannel mixtape. Fixie taxidermy synth, quinoa stumptown fashion axe brunch VHS hammock freegan lo-fi +1 offal irony. Sartorial single-origin coffee polaroid echo park asymmetrical meditation, jean shorts dreamcatcher butcher roof party affogato. Meggings small batch tacos, helvetica meditation lo-fi meh man braid shabby chic. YOLO offal before they sold out, normcore synth you probably haven't heard of them locavore migas whatever. Letterpress deep v wolf meditation crucifix.</p>
    </div>
  </div>
</div>

<h2 class="container subtitle">Current Public Games:</h2>

<% @games.each do |game| %>
<div class="game-card container">
  <div class="card-heading">
    <h3 class="card-title"><%= link_to "#{game.name}", game_path(game) %></h3>
  </div>
  <div class="game-wrapper">
      Game Master: <%= link_to "#{game.game_master.username}", game_master_path(game.game_master.id) %><br>
      <%= game.description %><br><br>
      <%= game.city %>, <%= game.state %><br><br>
  </div>
</div>
<% end %>

<footer>
  
</footer>